<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>SFS AI Assistant</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      background: transparent;
    }

    #chat-launcher {
      position: fixed;
      bottom: 20px;
      right: 20px;
      display: flex;
      align-items: center;
      z-index: 9999;
    }

    #chat-label {
      margin-right: 0.5cm;
      font-family: Arial, sans-serif;
      font-size: 14px;
      background-color: #fff;
      padding: 5px 10px;
      border-radius: 8px;
      box-shadow: 0 2px 6px rgba(0,0,0,0.1);
    }

    #chat-icon {
      width: 50px;
      height: 50px;
      background-color: #4b7bec;
      border-radius: 50%;
      cursor: pointer;
      background-image: url('https://cdn-icons-png.flaticon.com/512/4712/4712109.png');
      background-size: 60%;
      background-repeat: no-repeat;
      background-position: center;
    }

    #chat-overlay {
      display: none;
      position: fixed;
      top: 0;
      left: 0;
      width: 100vw;
      height: 100vh;
      z-index: 10000;
      background-color: white;
    }

    #chat-overlay iframe {
      width: 100%;
      height: 100%;
      border: none;
    }

    #chat-close {
      position: absolute;
      top: 10px;
      right: 20px;
      font-size: 24px;
      cursor: pointer;
      z-index: 10001;
      background: #fff;
      border-radius: 50%;
      padding: 5px 12px;
      box-shadow: 0 0 10px rgba(0,0,0,0.2);
    }
  </style>
</head>
<body>

  <div id="chat-launcher">
    <div id="chat-label">SFS AI ASSISTANT</div>
    <div id="chat-icon"></div>
  </div>

  <div id="chat-overlay">
    <div id="chat-close">&times;</div>
    <iframe src="https://www.chatbase.co/chatbot-iframe/9vcxm_e-MkeYCR4OxS0kF"></iframe>
  </div>

  <script>
    document.getElementById('chat-icon').addEventListener('click', function () {
      document.getElementById('chat-overlay').style.display = 'block';
    });

    document.getElementById('chat-close').addEventListener('click', function () {
      document.getElementById('chat-overlay').style.display = 'none';
    });
  </script>

</body>
</html>
